### PR TITLE
Feature/setup

### PR DESCRIPTION
**Pull request by lacyjpr**
Initial setup. Auth is working on the server side, client & server don't interact yet.

You'll need the config.json posted in our slack channel to get this to work.

Installation:

1. Pull down the branch with your preferred method.
2. git checkout feature/setup
3. "yarn install" to install dependencies
4. "yarn client-install" to install client dependencies
5. Add the config.json file to the config directory
6. "yarn dev" will start both the server & the client.

You should be able to see the client at http://localhost:3000/

The server is running at  http://localhost:5000

Navigating there should return "Cannot GET /"

Navigating to http://localhost:5000/auth/github should log you in with github but return "Cannot GET /auth/github/callback" You should see a github profile in your terminal

http://localhost:5000/api/current_user should return a JSON with the mongo id, your github id, user name & avatar url.

http://localhost:5000/api/logout will log you out & return a blank screen

### CODE REVIEW

**Comment by mbazhlekova** [comment]
I haven't had a chance to pull down the code and run it but it looks good to me. I'm good to merge into dev so we can start development. @aaronmassey45 what do you think?

**Comment by lacyjpr** [comment]
I wouldn't merge until you make sure it runs:)

Also, eslint settings need to be checked to make sure they're to everyone's liking!

**Comment by lacyjpr** [comment]
Fixed production routing issues.

Didn't want deployment problems popping up later. 

It's working at https://speedstudy-lacyjpr.herokuapp.com

You can play around with the app from there, or go to any of the above mentioned routes to make sure they're functioning as expected.

**Comment by mbazhlekova** [comment]
Checked out the project on heroku and all URLs work as expected. Good to merge!

**Comment by lacyjpr** [comment]
Don't want to merge unless it runs on both your machines:)

**Comment by lacyjpr** [comment]
Ok, I'll go ahead & merge.

Let me know if there are any issues!

**Pull request merged**
